import FadeUp from './FadeUp'

export default function WhatWeDo() {
  return <section id="what-we-do" className="py-20 bg-bg-alt" aria-labelledby="what-heading"><div className="max-w-container mx-auto px-6"><FadeUp className="mb-12"><span className="text-xs font-semibold uppercase tracking-widest text-accent">What we do</span><h2 id="what-heading" className="mt-2 text-3xl font-bold text-heading tracking-tight">Three things your front desk spends most of its time on.</h2></FadeUp><div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
    <div className="rounded-2xl border border-border bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md lg:col-span-2"><div className="mb-4 h-10 w-10 rounded-lg bg-accent/10 p-2 text-accent">📅</div><h3 className="mb-2 font-semibold text-heading">Scheduling</h3><p className="text-sm leading-relaxed text-body">Patients book, reschedule, and confirm visits at any hour. Your calendar stays full and your phones stay quiet.</p><div className="mt-6 rounded-xl border border-border p-3"><div className="mb-2 text-xs text-muted">Thursday 2:00 PM</div><div className="h-3 origin-left rounded-full bg-accent calendar-slot" /></div></div>
    <div className="rounded-2xl border border-border bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="mb-4 h-10 w-10 rounded-lg bg-accent/10 p-2 text-accent">💬</div><h3 className="mb-2 font-semibold text-heading">Patient Q&A</h3><p className="text-sm leading-relaxed text-body">Instant, accurate answers about hours, insurance, prep instructions, and follow-ups — in the channels patients already use.</p></div>
    <div className="rounded-2xl border border-border bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="mb-4 h-10 w-10 rounded-lg bg-accent/10 p-2 text-accent">▦</div><h3 className="mb-2 font-semibold text-heading">Workflow automation</h3><p className="text-sm leading-relaxed text-body">Intake, reminders, recalls, and routine follow-ups run on their own. Your team sets the rules.</p></div>
    <div className="rounded-2xl border border-border bg-white p-6 shadow-sm lg:col-span-2"><div className="grid grid-cols-3 items-center gap-3 text-center text-sm font-semibold text-heading"><span className="rounded-xl bg-bg-alt p-4">Patient message</span><span className="text-accent">→ Laxora AI →</span><span className="rounded-xl bg-accent/10 p-4 text-accent">Booked + notified</span></div></div>
  </div></div></section>
}
